import { db } from '@/db';
import { apps } from '@/db/schema';

async function main() {
    const sampleApps = [
        {
            name: 'Things 3',
            slug: 'things-3',
            developer: 'Cultured Code',
            description: 'Award-winning personal task manager that helps you achieve your goals.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$49.99',
            rating: 4.8,
            reviewsCount: 25430,
            iconUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/things-3',
            websiteUrl: 'https://culturedcode.com/things/',
            tags: JSON.stringify(['Task Management', 'GTD', 'Productivity', 'Calendar Integration']),
            features: JSON.stringify([
                'Beautiful, intuitive interface',
                'Project organization',
                'Calendar integration',
                'Today view',
                'Quick entry',
                'iCloud sync'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Bear',
            slug: 'bear',
            developer: 'Shiny Frog Ltd.',
            description: 'Beautiful, flexible writing app for crafting notes and prose.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 0,
            price: null,
            rating: 4.7,
            reviewsCount: 18920,
            iconUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/bear',
            websiteUrl: 'https://bear.app',
            tags: JSON.stringify(['Note Taking', 'Markdown', 'Writing', 'Organization']),
            features: JSON.stringify([
                'Markdown support',
                'Beautiful themes',
                'Cross-note links',
                'Export to multiple formats',
                'Advanced search',
                'Tags and hashtags'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Fantastical',
            slug: 'fantastical',
            developer: 'Flexibits Inc.',
            description: 'The calendar app you won\'t be able to live without.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$4.99/month',
            rating: 4.6,
            reviewsCount: 15230,
            iconUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1506784926709-22f1ec395907?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/fantastical',
            websiteUrl: 'https://flexibits.com/fantastical',
            tags: JSON.stringify(['Calendar', 'Scheduling', 'Events', 'Reminders']),
            features: JSON.stringify([
                'Natural language input',
                'Multiple calendar views',
                'Weather forecast',
                'Time zone support',
                'Meeting proposals',
                'Calendar sets'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Notability',
            slug: 'notability',
            developer: 'Ginger Labs',
            description: 'Powerful note-taking and annotation app.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 0,
            price: null,
            rating: 4.5,
            reviewsCount: 32100,
            iconUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/notability',
            websiteUrl: 'https://notability.com',
            tags: JSON.stringify(['Note Taking', 'Handwriting', 'PDF Annotation', 'Audio Recording']),
            features: JSON.stringify([
                'Handwriting and typing',
                'PDF annotation',
                'Audio recording',
                'Multi-note',
                'iCloud sync',
                'Apple Pencil support'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: '1Password',
            slug: '1password',
            developer: 'AgileBits Inc.',
            description: 'Password manager that\'s as beautiful and simple as it is secure.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$2.99/month',
            rating: 4.8,
            reviewsCount: 45670,
            iconUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1555421689-491a97ff2040?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/1password',
            websiteUrl: 'https://1password.com',
            tags: JSON.stringify(['Security', 'Password Manager', 'Encryption', 'Autofill']),
            features: JSON.stringify([
                'Secure password storage',
                'Watchtower security alerts',
                'Touch ID/Face ID',
                'Two-factor authentication',
                'Travel mode',
                'Family sharing'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Raycast',
            slug: 'raycast',
            developer: 'Raycast Technologies Inc.',
            description: 'Supercharged productivity tool for Mac. Control your tools with a few keystrokes.',
            category: 'Productivity',
            platform: 'macOS',
            isPaid: 0,
            price: null,
            rating: 4.9,
            reviewsCount: 12340,
            iconUrl: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://raycast.com',
            websiteUrl: 'https://raycast.com',
            tags: JSON.stringify(['Launcher', 'Productivity', 'Automation', 'Shortcuts']),
            features: JSON.stringify([
                'Quick access to apps and files',
                'Script commands',
                'Extensions marketplace',
                'Window management',
                'Clipboard history',
                'Calculator'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Sketch',
            slug: 'sketch',
            developer: 'Sketch B.V.',
            description: 'Professional digital design app for Mac.',
            category: 'Design',
            platform: 'macOS',
            isPaid: 1,
            price: '$99/year',
            rating: 4.7,
            reviewsCount: 8920,
            iconUrl: 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/sketch',
            websiteUrl: 'https://sketch.com',
            tags: JSON.stringify(['Design', 'UI/UX', 'Prototyping', 'Vector']),
            features: JSON.stringify([
                'Vector editing',
                'Symbols and components',
                'Prototyping',
                'Collaboration',
                'Cloud storage',
                'Plugin ecosystem'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Procreate',
            slug: 'procreate',
            developer: 'Savage Interactive',
            description: 'Most powerful and intuitive digital illustration app available for iPad.',
            category: 'Design',
            platform: 'iOS',
            isPaid: 1,
            price: '$12.99',
            rating: 4.8,
            reviewsCount: 67890,
            iconUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/procreate',
            websiteUrl: 'https://procreate.art',
            tags: JSON.stringify(['Drawing', 'Illustration', 'Art', 'Apple Pencil']),
            features: JSON.stringify([
                '136 brushes',
                'Advanced layer system',
                'Time-lapse recording',
                'QuickShape',
                'ColorDrop',
                'Apple Pencil support'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Affinity Designer',
            slug: 'affinity-designer',
            developer: 'Serif Labs',
            description: 'Professional graphic design software for desktop and iPad.',
            category: 'Design',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$54.99',
            rating: 4.6,
            reviewsCount: 5430,
            iconUrl: 'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1609921141835-710b7fa6e438?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/affinity-designer',
            websiteUrl: 'https://affinity.serif.com/designer',
            tags: JSON.stringify(['Design', 'Vector', 'Graphics', 'Professional']),
            features: JSON.stringify([
                'Vector and raster workflows',
                'Advanced typography',
                'Non-destructive effects',
                'Symbols and constraints',
                'Export options',
                'Apple Pencil support'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'OmniFocus',
            slug: 'omnifocus',
            developer: 'The Omni Group',
            description: 'Sophisticated task management for busy professionals.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$49.99',
            rating: 4.5,
            reviewsCount: 9120,
            iconUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/omnifocus',
            websiteUrl: 'https://www.omnigroup.com/omnifocus',
            tags: JSON.stringify(['GTD', 'Task Management', 'Productivity', 'Projects']),
            features: JSON.stringify([
                'GTD methodology',
                'Project and task hierarchy',
                'Custom perspectives',
                'Forecast view',
                'Review mode',
                'Automation support'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Craft',
            slug: 'craft',
            developer: 'Craft Docs',
            description: 'Built for digital devices from the ground up. Beautiful documents.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 0,
            price: null,
            rating: 4.7,
            reviewsCount: 14560,
            iconUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/craft-docs',
            websiteUrl: 'https://www.craft.do',
            tags: JSON.stringify(['Documents', 'Note Taking', 'Collaboration', 'Writing']),
            features: JSON.stringify([
                'Beautiful document editor',
                'Page linking',
                'Collaboration',
                'Templates',
                'Export options',
                'Daily notes'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Cardhop',
            slug: 'cardhop',
            developer: 'Flexibits Inc.',
            description: 'Contacts manager with natural language input.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$19.99',
            rating: 4.6,
            reviewsCount: 3210,
            iconUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1556745753-b2904692b3cd?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/cardhop',
            websiteUrl: 'https://flexibits.com/cardhop',
            tags: JSON.stringify(['Contacts', 'CRM', 'Organization', 'Natural Language']),
            features: JSON.stringify([
                'Natural language input',
                'Quick actions',
                'VIP contacts',
                'Birthday reminders',
                'Contact groups',
                'Social media integration'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'iA Writer',
            slug: 'ia-writer',
            developer: 'Information Architects',
            description: 'Distraction-free writing app designed for simplicity.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$29.99',
            rating: 4.7,
            reviewsCount: 11230,
            iconUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/ia-writer',
            websiteUrl: 'https://ia.net/writer',
            tags: JSON.stringify(['Writing', 'Markdown', 'Minimalist', 'Focus']),
            features: JSON.stringify([
                'Focus mode',
                'Syntax highlighting',
                'iCloud sync',
                'Export to multiple formats',
                'Content blocks',
                'Typewriter scrolling'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'CleanShot X',
            slug: 'cleanshot-x',
            developer: 'CleanShot',
            description: 'Capture your Mac\'s screen like a pro.',
            category: 'Utilities',
            platform: 'macOS',
            isPaid: 1,
            price: '$29',
            rating: 4.9,
            reviewsCount: 7890,
            iconUrl: 'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1547082299-de196ea013d6?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://cleanshot.com',
            websiteUrl: 'https://cleanshot.com',
            tags: JSON.stringify(['Screenshot', 'Screen Recording', 'Annotation', 'Utilities']),
            features: JSON.stringify([
                'Screenshot annotation',
                'Screen recording',
                'Cloud uploads',
                'Self-timer',
                'Hide desktop icons',
                'Quick access overlay'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Pixelmator Pro',
            slug: 'pixelmator-pro',
            developer: 'Pixelmator Team',
            description: 'Powerful, beautiful, and easy to use image editor.',
            category: 'Design',
            platform: 'macOS',
            isPaid: 1,
            price: '$49.99',
            rating: 4.8,
            reviewsCount: 13450,
            iconUrl: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/pixelmator-pro',
            websiteUrl: 'https://www.pixelmator.com/pro',
            tags: JSON.stringify(['Photo Editing', 'Design', 'Graphics', 'Layers']),
            features: JSON.stringify([
                'Advanced color adjustments',
                'Layer styles',
                'Non-destructive editing',
                'Machine learning enhancements',
                'RAW image editing',
                'Vector tools'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Ulysses',
            slug: 'ulysses',
            developer: 'Ulysses GmbH & Co. KG',
            description: 'The ultimate writing app for Mac, iPad and iPhone.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$5.99/month',
            rating: 4.6,
            reviewsCount: 9870,
            iconUrl: 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/ulysses',
            websiteUrl: 'https://ulysses.app',
            tags: JSON.stringify(['Writing', 'Markdown', 'Publishing', 'Organization']),
            features: JSON.stringify([
                'Distraction-free writing',
                'Library organization',
                'Publishing to WordPress & Medium',
                'Export to multiple formats',
                'Goals and statistics',
                'Attachment support'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Magnet',
            slug: 'magnet',
            developer: 'Crowded Road Ltd',
            description: 'Window manager for organized workspace.',
            category: 'Utilities',
            platform: 'macOS',
            isPaid: 1,
            price: '$7.99',
            rating: 4.7,
            reviewsCount: 21340,
            iconUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/magnet',
            websiteUrl: 'https://magnet.crowdcafe.com',
            tags: JSON.stringify(['Window Management', 'Productivity', 'Utilities', 'Shortcuts']),
            features: JSON.stringify([
                'Drag and drop windows',
                'Keyboard shortcuts',
                'Custom window sizes',
                'Multiple displays support',
                'Mission Control integration',
                'Quick window arrangements'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Tot',
            slug: 'tot',
            developer: 'The Iconfactory',
            description: 'Elegant, simple way to collect & edit text across your devices.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 0,
            price: null,
            rating: 4.8,
            reviewsCount: 6540,
            iconUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/tot',
            websiteUrl: 'https://tot.rocks',
            tags: JSON.stringify(['Notes', 'Quick Notes', 'Menu Bar', 'Sync']),
            features: JSON.stringify([
                'Seven dots for seven notes',
                'Menu bar quick access',
                'Markdown support',
                'iCloud sync',
                'URL schemes',
                'Minimalist design'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Goodlinks',
            slug: 'goodlinks',
            developer: 'ngrok LLC',
            description: 'Read-it-later app with powerful organization.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: 0,
            price: null,
            rating: 4.6,
            reviewsCount: 4320,
            iconUrl: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1556745753-b2904692b3cd?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/goodlinks',
            websiteUrl: 'https://goodlinks.app',
            tags: JSON.stringify(['Read Later', 'Bookmarks', 'Reading', 'Organization']),
            features: JSON.stringify([
                'Reader mode',
                'Tagging system',
                'Starred links',
                'Full-text search',
                'iCloud sync',
                'Share extension'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'PDF Expert',
            slug: 'pdf-expert',
            developer: 'Readdle Inc.',
            description: 'Fast, robust and beautiful PDF editor.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 0,
            price: null,
            rating: 4.7,
            reviewsCount: 28910,
            iconUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/pdf-expert',
            websiteUrl: 'https://pdfexpert.com',
            tags: JSON.stringify(['PDF', 'Documents', 'Annotation', 'Editing']),
            features: JSON.stringify([
                'Edit PDF text and images',
                'Fill forms',
                'Annotate and sign',
                'Merge and split PDFs',
                'Redact sensitive info',
                'Cloud storage integration'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Drafts',
            slug: 'drafts',
            developer: 'Agile Tortoise',
            description: 'Where text starts. Capture, transform, and send your ideas.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 0,
            price: null,
            rating: 4.8,
            reviewsCount: 15670,
            iconUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/drafts',
            websiteUrl: 'https://getdrafts.com',
            tags: JSON.stringify(['Note Taking', 'Automation', 'Quick Capture', 'Scripting']),
            features: JSON.stringify([
                'Quick capture',
                'Actions and integrations',
                'JavaScript scripting',
                'Workspaces',
                'Themes and syntax',
                'iCloud sync'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Darkroom',
            slug: 'darkroom',
            developer: 'Bergen Co.',
            description: 'Premium photo & video editor.',
            category: 'Design',
            platform: 'iOS',
            isPaid: 0,
            price: null,
            rating: 4.7,
            reviewsCount: 19230,
            iconUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/darkroom',
            websiteUrl: 'https://darkroom.co',
            tags: JSON.stringify(['Photo Editing', 'Filters', 'RAW', 'Video Editing']),
            features: JSON.stringify([
                'RAW photo editing',
                'Curve adjustments',
                'Batch editing',
                'Presets',
                'Video editing',
                'iCloud sync'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Paste',
            slug: 'paste',
            developer: 'FunctionCode LLC',
            description: 'The best clipboard manager for Mac and iOS.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$1.99/month',
            rating: 4.6,
            reviewsCount: 8760,
            iconUrl: 'https://images.unsplash.com/photo-1555421689-491a97ff2040?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1555421689-491a97ff2040?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/paste',
            websiteUrl: 'https://pasteapp.io',
            tags: JSON.stringify(['Clipboard', 'Productivity', 'History', 'Sync']),
            features: JSON.stringify([
                'Unlimited clipboard history',
                'Pinboards',
                'iCloud sync',
                'Smart search',
                'Custom rules',
                'Quick paste'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Working Copy',
            slug: 'working-copy',
            developer: 'Anders Borum',
            description: 'Powerful Git client for iOS.',
            category: 'Developer Tools',
            platform: 'iOS',
            isPaid: 0,
            price: null,
            rating: 4.9,
            reviewsCount: 5430,
            iconUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/working-copy',
            websiteUrl: 'https://workingcopy.app',
            tags: JSON.stringify(['Git', 'Version Control', 'Development', 'Code']),
            features: JSON.stringify([
                'Full Git client',
                'Commit and push',
                'Pull requests',
                'Syntax highlighting',
                'SSH keys',
                'External editor support'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Taio',
            slug: 'taio',
            developer: 'Nebo Apps LLC',
            description: 'Text actions and editing for iOS.',
            category: 'Productivity',
            platform: 'iOS',
            isPaid: 0,
            price: null,
            rating: 4.7,
            reviewsCount: 4120,
            iconUrl: 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/taio',
            websiteUrl: 'https://taio.app',
            tags: JSON.stringify(['Text Editor', 'Automation', 'Markdown', 'Actions']),
            features: JSON.stringify([
                'Text actions',
                'JavaScript automation',
                'Markdown support',
                'Snippets',
                'iCloud sync',
                'Share extension'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'MindNode',
            slug: 'mindnode',
            developer: 'IdeasOnCanvas GmbH',
            description: 'Delightful mind mapping.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$2.99/month',
            rating: 4.6,
            reviewsCount: 7890,
            iconUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/mindnode',
            websiteUrl: 'https://mindnode.com',
            tags: JSON.stringify(['Mind Mapping', 'Brainstorming', 'Visual Thinking', 'Organization']),
            features: JSON.stringify([
                'Visual mind mapping',
                'Task management',
                'Stickers and themes',
                'Quick entry',
                'Export options',
                'iCloud sync'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Reeder',
            slug: 'reeder',
            developer: 'Silvio Rizzi',
            description: 'News reader for Feedbin, Feedly, Feed Wrangler, and more.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: 1,
            price: '$9.99',
            rating: 4.8,
            reviewsCount: 12340,
            iconUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1516321497487-e288fb19713f?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1556745753-b2904692b3cd?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/reeder',
            websiteUrl: 'https://reederapp.com',
            tags: JSON.stringify(['RSS', 'News Reader', 'Feeds', 'Reading']),
            features: JSON.stringify([
                'Multiple service support',
                'Beautiful reading experience',
                'Bionic reading mode',
                'Read-later integration',
                'Customizable gestures',
                'iCloud sync'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'DEVONthink',
            slug: 'devonthink',
            developer: 'DEVONtechnologies LLC',
            description: 'Document and information management.',
            category: 'Productivity',
            platform: 'macOS',
            isPaid: 1,
            price: '$99',
            rating: 4.5,
            reviewsCount: 4560,
            iconUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/devonthink',
            websiteUrl: 'https://devontechnologies.com/apps/devonthink',
            tags: JSON.stringify(['Document Management', 'Research', 'Knowledge Base', 'Archiving']),
            features: JSON.stringify([
                'Universal inbox',
                'Smart groups',
                'Full-text search',
                'OCR',
                'Web clipper',
                'Sync options'
            ]),
            isFeatured: 0,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Scriptable',
            slug: 'scriptable',
            developer: 'Simon B. Støvring',
            description: 'Automation using JavaScript.',
            category: 'Developer Tools',
            platform: 'iOS',
            isPaid: 0,
            price: null,
            rating: 4.8,
            reviewsCount: 11230,
            iconUrl: 'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/scriptable',
            websiteUrl: 'https://scriptable.app',
            tags: JSON.stringify(['Automation', 'JavaScript', 'Widgets', 'Scripting']),
            features: JSON.stringify([
                'JavaScript automation',
                'Custom widgets',
                'Shortcuts integration',
                'File system access',
                'Web requests',
                'Rich text editor'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        },
        {
            name: 'Halide',
            slug: 'halide',
            developer: 'Lux Optics',
            description: 'Professional camera app for iPhone.',
            category: 'Design',
            platform: 'iOS',
            isPaid: 0,
            price: null,
            rating: 4.7,
            reviewsCount: 14670,
            iconUrl: 'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1550859492-d5da9d8e45f3?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/halide',
            websiteUrl: 'https://halide.cam',
            tags: JSON.stringify(['Photography', 'RAW', 'Manual Controls', 'Camera']),
            features: JSON.stringify([
                'Manual controls',
                'RAW capture',
                'Focus peaking',
                'Depth capture',
                'Smart RAW',
                'ProRAW support'
            ]),
            isFeatured: 1,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        }
    ];

    await db.insert(apps).values(sampleApps);
    
    console.log('✅ Apps seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});