import { db } from '@/db';
import { apps } from '@/db/schema';

async function main() {
    const sampleApps = [
        {
            name: 'Things 3',
            slug: 'things-3',
            developer: 'Cultured Code',
            description: 'Award-winning personal task manager with beautiful design and powerful features for organizing your life and work.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$49.99',
            rating: 4.8,
            reviewsCount: 45000,
            iconUrl: 'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1484480974693-6ca0a78fb36b?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/things-3/id904237743',
            websiteUrl: 'https://culturedcode.com/things/',
            tags: JSON.stringify(['tasks', 'productivity', 'GTD', 'planning']),
            features: JSON.stringify(['Natural language input', 'Today view', 'Calendar integration', 'Projects & Areas']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Bear',
            slug: 'bear',
            developer: 'Shiny Frog',
            description: 'Beautiful, flexible writing app for notes and prose. Perfect for everything from quick notes to in-depth essays.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: false,
            price: null,
            rating: 4.7,
            reviewsCount: 38000,
            iconUrl: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/bear/id1016366447',
            websiteUrl: 'https://bear.app',
            tags: JSON.stringify(['notes', 'markdown', 'writing', 'sync']),
            features: JSON.stringify(['Markdown support', 'Tags & nested tags', 'Advanced search', 'Export to multiple formats']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Fantastical',
            slug: 'fantastical',
            developer: 'Flexibits',
            description: 'The calendar app you won\'t be able to live without. Natural language parsing, weather forecasts, and beautiful design.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$4.99/month',
            rating: 4.6,
            reviewsCount: 32000,
            iconUrl: 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/fantastical/id718043190',
            websiteUrl: 'https://flexibits.com/fantastical',
            tags: JSON.stringify(['calendar', 'scheduling', 'reminders', 'weather']),
            features: JSON.stringify(['Natural language input', 'Calendar sets', 'Weather integration', 'Time zone support']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Notability',
            slug: 'notability',
            developer: 'Ginger Labs',
            description: 'Powerful note-taking app for iPad and Mac. Combine handwriting, photos, and typing in a single note.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$14.99',
            rating: 4.7,
            reviewsCount: 67000,
            iconUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1512314889357-e157c22f938d?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/notability/id360593530',
            websiteUrl: 'https://notability.com',
            tags: JSON.stringify(['notes', 'handwriting', 'PDF', 'annotation']),
            features: JSON.stringify(['Handwriting recognition', 'Audio recording', 'PDF annotation', 'iCloud sync']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'OmniFocus',
            slug: 'omnifocus',
            developer: 'The Omni Group',
            description: 'Professional-grade task management for serious users. GTD methodology built-in with powerful automation.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$49.99',
            rating: 4.5,
            reviewsCount: 18000,
            iconUrl: 'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1507925921958-8a62f3d1a50d?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/omnifocus-3/id1346190318',
            websiteUrl: 'https://www.omnigroup.com/omnifocus',
            tags: JSON.stringify(['tasks', 'GTD', 'productivity', 'automation']),
            features: JSON.stringify(['Perspectives', 'Forecast view', 'Review mode', 'Automation with JavaScript']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Craft',
            slug: 'craft',
            developer: 'Luki Labs',
            description: 'Beautiful documents and notes with powerful features. Perfect for personal and team collaboration.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: false,
            price: null,
            rating: 4.8,
            reviewsCount: 28000,
            iconUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/craft-docs-and-notes-editor/id1487937127',
            websiteUrl: 'https://www.craft.do',
            tags: JSON.stringify(['notes', 'documents', 'collaboration', 'design']),
            features: JSON.stringify(['Beautiful templates', 'Real-time collaboration', 'Web publishing', 'Deep linking']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Cardhop',
            slug: 'cardhop',
            developer: 'Flexibits',
            description: 'Contacts manager with natural language input and powerful search. Integrates perfectly with your existing contacts.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$19.99',
            rating: 4.6,
            reviewsCount: 8500,
            iconUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1556742393-d75f468bfcb0?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/cardhop/id1290358394',
            websiteUrl: 'https://flexibits.com/cardhop',
            tags: JSON.stringify(['contacts', 'address book', 'natural language', 'search']),
            features: JSON.stringify(['Natural language parsing', 'Quick actions', 'Groups management', 'Custom fields']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'iA Writer',
            slug: 'ia-writer',
            developer: 'iA',
            description: 'Pure, distraction-free writing environment with powerful focus mode and syntax highlighting.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$49.99',
            rating: 4.7,
            reviewsCount: 22000,
            iconUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/ia-writer/id775737172',
            websiteUrl: 'https://ia.net/writer',
            tags: JSON.stringify(['writing', 'markdown', 'focus', 'minimalist']),
            features: JSON.stringify(['Focus Mode', 'Syntax highlighting', 'Templates', 'Export to multiple formats']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Ulysses',
            slug: 'ulysses',
            developer: 'Ulysses GmbH',
            description: 'Professional writing environment for Mac, iPad, and iPhone. Loved by writers for its powerful organization.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$5.99/month',
            rating: 4.6,
            reviewsCount: 15000,
            iconUrl: 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/ulysses/id1225570693',
            websiteUrl: 'https://ulysses.app',
            tags: JSON.stringify(['writing', 'markdown', 'publishing', 'organization']),
            features: JSON.stringify(['Library organization', 'Goals tracking', 'Publishing tools', 'Markup-based writing']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'PDF Expert',
            slug: 'pdf-expert',
            developer: 'Readdle',
            description: 'The ultimate PDF editor for Mac and iOS. Read, annotate, and edit PDFs with powerful tools.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$79.99',
            rating: 4.7,
            reviewsCount: 42000,
            iconUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/pdf-expert-pdf-editor/id743974925',
            websiteUrl: 'https://pdfexpert.com',
            tags: JSON.stringify(['PDF', 'annotation', 'editing', 'forms']),
            features: JSON.stringify(['PDF editing', 'Form filling', 'Annotations', 'Cloud integration']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Drafts',
            slug: 'drafts',
            developer: 'Agile Tortoise',
            description: 'Where text starts on iOS and Mac. Capture text quickly and send it anywhere with powerful actions.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: false,
            price: null,
            rating: 4.8,
            reviewsCount: 19000,
            iconUrl: 'https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1512486130939-2c4f79935e4f?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/drafts/id1435957248',
            websiteUrl: 'https://getdrafts.com',
            tags: JSON.stringify(['notes', 'quick capture', 'automation', 'actions']),
            features: JSON.stringify(['Quick capture', 'Custom actions', 'Keyboard shortcuts', 'URL schemes']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'MindNode',
            slug: 'mindnode',
            developer: 'IdeasOnCanvas',
            description: 'Beautiful mind mapping for Mac and iOS. Organize thoughts and ideas visually with elegant design.',
            category: 'Productivity',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$19.99',
            rating: 4.6,
            reviewsCount: 12000,
            iconUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/mindnode-mind-map-outline/id1218718027',
            websiteUrl: 'https://www.mindnode.com',
            tags: JSON.stringify(['mind mapping', 'brainstorming', 'visualization', 'organization']),
            features: JSON.stringify(['Visual thinking', 'Smart layout', 'Quick entry', 'Export options']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'DEVONthink',
            slug: 'devonthink',
            developer: 'DEVONtechnologies',
            description: 'Document and information management powerhouse. Store, organize, and find all your documents.',
            category: 'Productivity',
            platform: 'macOS',
            isPaid: true,
            price: '$99.99',
            rating: 4.5,
            reviewsCount: 6500,
            iconUrl: 'https://images.unsplash.com/photo-1568667256549-094345857637?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1568667256549-094345857637?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/devonthink-3/id1546487358',
            websiteUrl: 'https://www.devontechnologies.com',
            tags: JSON.stringify(['documents', 'organization', 'research', 'database']),
            features: JSON.stringify(['AI-powered organization', 'Full-text search', 'Smart groups', 'OCR']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Sketch',
            slug: 'sketch',
            developer: 'Sketch B.V.',
            description: 'Professional digital design toolkit for Mac. Create user interfaces, websites, and icons.',
            category: 'Design',
            platform: 'macOS',
            isPaid: true,
            price: '$9/month',
            rating: 4.7,
            reviewsCount: 35000,
            iconUrl: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/sketch/id852320343',
            websiteUrl: 'https://www.sketch.com',
            tags: JSON.stringify(['design', 'UI', 'vector', 'prototyping']),
            features: JSON.stringify(['Vector editing', 'Symbols', 'Prototyping', 'Collaboration']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Procreate',
            slug: 'procreate',
            developer: 'Savage Interactive',
            description: 'Award-winning digital illustration app for iPad. Professional-grade tools in an intuitive interface.',
            category: 'Design',
            platform: 'iOS',
            isPaid: true,
            price: '$12.99',
            rating: 4.9,
            reviewsCount: 70000,
            iconUrl: 'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/procreate/id425073498',
            websiteUrl: 'https://procreate.com',
            tags: JSON.stringify(['illustration', 'painting', 'drawing', 'digital art']),
            features: JSON.stringify(['136 brushes', 'Layer system', 'Time-lapse replay', 'PSD support']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Affinity Designer',
            slug: 'affinity-designer',
            developer: 'Serif Labs',
            description: 'Professional vector graphics software. Fast, smooth, and precise alternative to Adobe Illustrator.',
            category: 'Design',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$69.99',
            rating: 4.7,
            reviewsCount: 18000,
            iconUrl: 'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/affinity-designer-2/id1616831348',
            websiteUrl: 'https://affinity.serif.com/designer/',
            tags: JSON.stringify(['vector', 'design', 'illustration', 'professional']),
            features: JSON.stringify(['Vector & raster', 'Non-destructive', 'Precise controls', 'Export options']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Pixelmator Pro',
            slug: 'pixelmator-pro',
            developer: 'Pixelmator Team',
            description: 'Powerful image editor for Mac with machine learning features and professional tools.',
            category: 'Design',
            platform: 'macOS',
            isPaid: true,
            price: '$49.99',
            rating: 4.8,
            reviewsCount: 24000,
            iconUrl: 'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/pixelmator-pro/id1289583905',
            websiteUrl: 'https://www.pixelmator.com/pro/',
            tags: JSON.stringify(['photo editing', 'design', 'machine learning', 'layers']),
            features: JSON.stringify(['ML-powered editing', 'RAW support', 'Vector tools', 'Non-destructive']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Darkroom',
            slug: 'darkroom',
            developer: 'Bergen Co.',
            description: 'Powerful photo and video editor designed for speed. Professional tools in an elegant interface.',
            category: 'Design',
            platform: 'iOS',
            isPaid: false,
            price: null,
            rating: 4.8,
            reviewsCount: 26000,
            iconUrl: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/darkroom-photo-video-editor/id953286746',
            websiteUrl: 'https://darkroom.co',
            tags: JSON.stringify(['photo editing', 'filters', 'RAW', 'batch editing']),
            features: JSON.stringify(['RAW editing', 'Batch editing', 'Curves & color', 'Video editing']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Halide',
            slug: 'halide',
            developer: 'Lux Optics',
            description: 'Professional manual camera for iPhone. Take full control with advanced features and RAW support.',
            category: 'Design',
            platform: 'iOS',
            isPaid: true,
            price: '$11.99',
            rating: 4.7,
            reviewsCount: 15000,
            iconUrl: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/halide-mark-ii-pro-camera/id885697368',
            websiteUrl: 'https://halide.cam',
            tags: JSON.stringify(['camera', 'photography', 'RAW', 'manual controls']),
            features: JSON.stringify(['Manual controls', 'RAW capture', 'Focus peaking', 'Depth capture']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: '1Password',
            slug: '1password',
            developer: 'AgileBits',
            description: 'The world\'s most-loved password manager. Secure storage for passwords, documents, and more.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$2.99/month',
            rating: 4.7,
            reviewsCount: 55000,
            iconUrl: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1582139329536-e7284fece509?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/1password-password-manager/id1333542190',
            websiteUrl: 'https://1password.com',
            tags: JSON.stringify(['password manager', 'security', 'encryption', 'sync']),
            features: JSON.stringify(['Password generator', 'Watchtower', 'Travel Mode', 'Secure sharing']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'CleanShot X',
            slug: 'cleanshot-x',
            developer: 'MacPaw',
            description: 'The best screenshot and screen recording app for Mac. Powerful tools for capturing and annotating.',
            category: 'Utilities',
            platform: 'macOS',
            isPaid: true,
            price: '$29/year',
            rating: 4.9,
            reviewsCount: 12000,
            iconUrl: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/cleanshot-x/id1447089101',
            websiteUrl: 'https://cleanshot.com',
            tags: JSON.stringify(['screenshots', 'screen recording', 'annotation', 'productivity']),
            features: JSON.stringify(['Scrolling capture', 'Cloud upload', 'Annotation tools', 'Self-timer']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Magnet',
            slug: 'magnet',
            developer: 'Pixel Hect',
            description: 'Window manager for Mac. Organize your workspace with keyboard shortcuts and drag actions.',
            category: 'Utilities',
            platform: 'macOS',
            isPaid: true,
            price: '$9.99',
            rating: 4.6,
            reviewsCount: 28000,
            iconUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/magnet/id441258766',
            websiteUrl: null,
            tags: JSON.stringify(['window management', 'productivity', 'keyboard shortcuts', 'organization']),
            features: JSON.stringify(['Keyboard shortcuts', 'Drag to edges', 'Custom layouts', 'Multi-display']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Tot',
            slug: 'tot',
            developer: 'The Iconfactory',
            description: 'Elegant, simple way to collect text. Seven tiny text documents, always available on your menu bar.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$19.99',
            rating: 4.7,
            reviewsCount: 8500,
            iconUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/tot/id1491071483',
            websiteUrl: 'https://tot.rocks',
            tags: JSON.stringify(['notes', 'quick capture', 'minimalist', 'menu bar']),
            features: JSON.stringify(['Seven dots', 'Format bar', 'Character count', 'iCloud sync']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Goodlinks',
            slug: 'goodlinks',
            developer: 'Ngoc Luu',
            description: 'Beautiful read-it-later app for saving and organizing articles. Clean design with powerful features.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$7.99',
            rating: 4.8,
            reviewsCount: 9500,
            iconUrl: 'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/goodlinks/id1474335294',
            websiteUrl: 'https://goodlinks.app',
            tags: JSON.stringify(['read later', 'articles', 'bookmarks', 'reading']),
            features: JSON.stringify(['Reader mode', 'Tags', 'Full-text search', 'iCloud sync']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Paste',
            slug: 'paste',
            developer: 'FogoSoft',
            description: 'Clipboard manager that keeps everything you copy. Never lose important clipboard content again.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$1.99/month',
            rating: 4.7,
            reviewsCount: 16000,
            iconUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/paste-clipboard-manager/id967805235',
            websiteUrl: 'https://pasteapp.io',
            tags: JSON.stringify(['clipboard', 'productivity', 'history', 'sync']),
            features: JSON.stringify(['Unlimited history', 'Smart search', 'Pinboard', 'iCloud sync']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Reeder',
            slug: 'reeder',
            developer: 'Silvio Rizzi',
            description: 'Beautiful RSS reader with gesture controls and support for multiple services.',
            category: 'Utilities',
            platform: 'Cross-platform',
            isPaid: true,
            price: '$9.99',
            rating: 4.7,
            reviewsCount: 11000,
            iconUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1499951360447-b19be8fe80f5?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/reeder-5/id1529445840',
            websiteUrl: 'https://reederapp.com',
            tags: JSON.stringify(['RSS', 'news', 'reading', 'feeds']),
            features: JSON.stringify(['Multiple services', 'Gesture controls', 'Read later', 'Dark mode']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Raycast',
            slug: 'raycast',
            developer: 'Raycast Technologies',
            description: 'Blazingly fast launcher for developers. Supercharge your productivity with extensions and shortcuts.',
            category: 'Developer Tools',
            platform: 'macOS',
            isPaid: false,
            price: null,
            rating: 4.9,
            reviewsCount: 32000,
            iconUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/raycast/id1438243524',
            websiteUrl: 'https://raycast.com',
            tags: JSON.stringify(['launcher', 'productivity', 'developer', 'automation']),
            features: JSON.stringify(['Extensions store', 'Script commands', 'Snippets', 'Window management']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Working Copy',
            slug: 'working-copy',
            developer: 'Anders Borum',
            description: 'Powerful Git client for iOS and iPadOS. Clone, edit, commit, and push right from your device.',
            category: 'Developer Tools',
            platform: 'iOS',
            isPaid: false,
            price: null,
            rating: 4.8,
            reviewsCount: 14000,
            iconUrl: 'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/working-copy-git-client/id896694807',
            websiteUrl: 'https://workingcopyapp.com',
            tags: JSON.stringify(['git', 'version control', 'developer', 'coding']),
            features: JSON.stringify(['Full Git support', 'Syntax highlighting', 'SSH keys', 'External editor']),
            isFeatured: true,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            name: 'Scriptable',
            slug: 'scriptable',
            developer: 'Simon B. Støvring',
            description: 'Automation using JavaScript on iOS. Create scripts that interact with native features of iOS.',
            category: 'Developer Tools',
            platform: 'iOS',
            isPaid: false,
            price: null,
            rating: 4.8,
            reviewsCount: 19000,
            iconUrl: 'https://images.unsplash.com/photo-1517842645767-c639042777db?w=200&h=200&fit=crop',
            screenshotUrls: JSON.stringify([
                'https://images.unsplash.com/photo-1517842645767-c639042777db?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&h=600&fit=crop',
                'https://images.unsplash.com/photo-1556075798-4825dfaaf498?w=800&h=600&fit=crop'
            ]),
            appStoreUrl: 'https://apps.apple.com/app/scriptable/id1405459188',
            websiteUrl: 'https://scriptable.app',
            tags: JSON.stringify(['automation', 'javascript', 'widgets', 'developer']),
            features: JSON.stringify(['JavaScript API', 'Widgets', 'Siri shortcuts', 'Share sheet']),
            isFeatured: false,
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ];

    await db.insert(apps).values(sampleApps);
    
    console.log('✅ Apps seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});